In [1]:
import torch 
import sys
from torch_geometric.data import Data
from datasets.graph_datasets.graph_data_utils import generate_discretised_graph
sys.path.append('..')

/Users/louisgodtfredsen/Desktop/Coding Projects/ML-for-PDEs/.venv/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
data_path ='../data/test_data/heat_equation_m64_h0_minmax_N200.pt'
input_data = torch.load(data_path)

In [3]:
input_data['X'][0,0].shape

torch.Size([64, 64])

In [4]:
H = 64
x_y_units = torch.tensor([(1/H)*x for x in range(H)])
pos_tensor = torch.cartesian_prod(x_y_units, x_y_units)

In [5]:
pos_tensor

tensor([[0.0000, 0.0000],
        [0.0000, 0.0156],
        [0.0000, 0.0312],
        ...,
        [0.9844, 0.9531],
        [0.9844, 0.9688],
        [0.9844, 0.9844]])

In [6]:
edge_idx, edge_disp, node_indices = generate_discretised_graph(input_data['X'][0,0], 0.025, 'periodic')

print(edge_idx.shape)
print(edge_disp.shape)

torch.Size([2, 32768])
torch.Size([32768, 2])


In [ ]:
node_indices

tensor([[ 0,  0],
        [ 0,  1],
        [ 0,  2],
        ...,
        [63, 61],
        [63, 62],
        [63, 63]])

In [8]:
edge_disp[edge_idx[0, :] == 0, :]

tensor([[ 0.0000, -0.0156],
        [ 0.0000,  0.0156],
        [-0.0156,  0.0000],
        [-0.0156, -0.0156],
        [-0.0156,  0.0156],
        [ 0.0156,  0.0000],
        [ 0.0156, -0.0156],
        [ 0.0156,  0.0156]])

In [9]:
edge_idx

tensor([[   0,    0,    0,  ..., 4095, 4095, 4095],
        [   1,   63,   64,  ..., 4031, 4032, 4094]])